### PR TITLE
Correct license and correct author field

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by Joozty** [comment]
@viktor-yakubiv This is how we should have it everywhere. Will start to change it in all our projects.

**Comment by viktor-yakubiv** [comment]
We should change the license file too then.

**Comment by Joozty** [comment]
What would you put there? I read somewhere that when you don't provide LICENSE file in repo it automatically means it's unlicensed.

**Comment by viktor-yakubiv** [comment]
I am not sure [UNLICENSE](https://unlicense.org) is the one but if it is the actual meaning of being unlicensed, it would prefer MIT.

**Comment by Joozty** [comment]
It's unlicensed and it is supposed to be something different. I was following this guide - https://docs.npmjs.com/files/package.json#license (scroll down at the end of license section)

**Pull request merged**
