### PR TITLE
Replace portal with context API in SearchBar

### PR DESCRIPTION
**Pull request by Joozty**
This is the first step in order to use the new header component. Sadly the select component is still not prerendered. The only change here is that search bar is rendered in the middle and there is no need to use `order` rule. 

The PR introduces new hook `useSearchBar` which controls search bar in the header. It's done with help of Context API

### CODE REVIEW

**Review by viktor-yakubiv — COMMENTED** [review]
Are you happy with the result/approach?

**Review by viktor-yakubiv — APPROVED** [review]
I recently thought that passing a prop to Page component is a more correct way to handle this problem because it's more controllable top-down, i.e. it cannot be used in the child component and parent component in the same time if the parent doesn't allow it.

However, I like the current solution. It's very good. Thanks a lot for moving this forward! 🙂

**Comment by Joozty** [comment]
You mean like in controlling it in `_app.jsx`? This is the downside of the solution. It can be used in many places at the same time. I expect that we are clever enough to avoid it. I agree it's not optimal but on the other hand, I wanted to keep all logic in the template.


I don't have a strong preference here. I find it neutral whether it was portal or context. From this point of view, I see one very small detail that in order to enable search the whole app needs to be rerendered.

**Comment by viktor-yakubiv** [comment]
Yes, I mean, passing a callback function from the App to a (Page) Component as a prop would save us from the multiple uses.

**Comment by Joozty** [comment]
true, maybe you should have told me sooner. 😄 I am too lazy to change it now. Maybe later.

**Comment by viktor-yakubiv** [comment]
Sure, I was thinking about already when you started implementing. I wish I could force my brain to think about sooner but unfortunately, it's not how it works 😄 I am happy with the current implementation.

**Pull request merged**
