### PR TITLE
Make map taller

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
I meant taller, not wider. Width satisfied me enough. It's okay now too but it's better to make it taller.

**Comment by Joozty** [comment]
I guess I will need to add another breakpoint for tablet screens (decrease the page padding and make search -map - 50% - 50%) so it looks better.

**Comment by Joozty** [comment]
@viktor-yakubiv Please have a look now :)

**Comment by viktor-yakubiv** [comment]
@Joozty we definitely should think more about everything not only about one breakpoint 😄

This is the window about 750px wide:

Data providers page on the 750px

**Comment by Joozty** [comment]
I would say some styles don't apply on safari. My looks better (it's not perfect but it doesn't overflow)


Capture

**Comment by viktor-yakubiv** [comment]
I start hating that everybody stops supporting Safari. But it's personal, I don't mind we don't support it 😄

**Review by viktor-yakubiv — APPROVED** [review]
Smart solution, I like it 👍

**Comment by Joozty** [comment]
I would support it if I had a mac. But like it's really hard for me to properly support it. Browserstack is too slow for me and it's hard to do something meaningful there. I will check it though. Especially the slowness warning.

**Pull request merged**
