### PR TITLE
Add pagination

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by Joozty** [comment]
One thing I noticed is that when you hit the load more button user should be scrolled to the last result before the new chunk is loaded. I didn't handle this case yet and consider it out of scope. However, I will this case once at some point (probably once this pagination style is approved petr) if that's ok with you @viktor-yakubiv .

**Review by viktor-yakubiv — COMMENTED** [review]
I get an infinite refresh

**Comment by Joozty** [comment]
Can you please hard refresh? It looks like you have old version cached? 🤔 I fixed it already

**Comment by viktor-yakubiv** [comment]
> Can you please hard refresh? It looks like you have old version cached

I experience the same behaviour (refreshes) in every browser I have. I didn't open this page before in some of them so I doubt it the cache problem.

**Comment by Joozty** [comment]
Oh I broke the data-providers page.I will fix it

**Review by viktor-yakubiv — APPROVED** [review]
It looks good to me. Good job!

I think if you 'load more' and then go to next, it should go to 21-30, not to 11-20 because it was already loaded.

**Pull request merged**
